name: A-Team Common
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test-firmware-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Validate Nix Envoirnment
        shell: bash
        run: |
          nix flake check
          nix develop -c cargo --version
      - name: Build Common Items
        shell: bash
        run: |
          nix develop -c make bindgen-packets
      - name: Test Common Items
        shell: bash
        run: |
          nix develop -c make bindgen-packets-test
      - name: Test Proto Plugin
        shell: bash
        run: |
          nix develop -c make proto-plugin-test
      - name: Test Proto C++ Conversion Plugin
        shell: bash
        run: |
          nix develop -c make proto-cpp-plugin-test
      - name: Test SSL League Proto Compatibility
        shell: bash
        run: |
          nix develop -c make ssl-proto-test
